const { PYTHON, HTML, PROCESSING, REACT } = require("../../../constants");

const SketchThumbnailArray = [
  "Ant",
  "Badger",
  "Bear",
  "Beaver",
  "Bird",
  "Bug",
  "Bull",
  "Bumblebee",
  "Butterfly",
  "Cat",
  "Caterpillar",
  "Chicken",
  "Clown Fish",
  "Corgi",
  "Cow",
  "Crab",
  "Deer",
  "Dinosaur",
  "Dog",
  "Dolphin",
  "Dragonfly",
  "Duck",
  "Elephant",
  "Falcon",
  "Fish",
  "Fly",
  "Frog",
  "Giraffe",
  "Gorilla",
  "Grasshopper",
  "Horse",
  "Hummingbird",
  "Insect",
  "Kangaroo",
  "Kiwi Bird",
  "Ladybird",
  "Leopard",
  "Lion",
  "Llama",
  "Mite",
  "Mosquito",
  "Octopus",
  "Panda",
  "Prawn",
  "Puffin Bird",
  "Rabbit",
  "Rhinoceros",
  "Seahorse",
  "Shark",
  "Sheep",
  "Snail",
  "Spider",
  "Starfish",
  "Stork",
  "Turtle",
  "Unicorn",
  "Whale",
  "Wolf",
];

const LanguageDropdownValues = [
  { display: "Python", value: PYTHON },
  { display: "Processing", value: PROCESSING },
  { display: "React", value: REACT },
  { display: "HTML", value: HTML },
];

const LanguageDropdownDefault = { display: "Python", value: PYTHON };

module.exports = {
  SketchThumbnailArray,
  LanguageDropdownValues,
  LanguageDropdownDefault,
};
