name: Lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Run ESlint
      run: |
        git fetch origin master
        npm run lint-js-changes
    - name: Run Stylelint
      run: |
        git fetch origin master
        npm run lint-css-changes
